#version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ParthaSDas@22
      MYSQL_DATABASE: banking_application
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  banking-app:
    image: banking-app:latest   # your Spring Boot Docker image
    container_name: banking-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/banking_application
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ParthaSDas@22
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
    depends_on:
      - mysql-db

volumes:
  mysql-data:
